server:
  servlet:
    context-path: /api
spring:
  application:
    name: Admin API
  datasource:
    url: jdbc:h2:mem:admin_dbDB_CLOSE_DELAY=-1;MODE=MySQL;NON_KEYWORDS=USER
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
  h2:
    console.enabled: true



logging:
  level:
    com:
      h2database: DEBUG
security:
  jwt:
    secretKey: SECRETKEY


